export const BREADCRUMB_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  pos: 'Point of Sale',
  products: 'Products',
  categories: 'Categories',
  inventory: 'Inventory',
  adjustments: 'Adjustments',
  alerts: 'Low Stock Alerts',
  sales: 'Sales',
  customers: 'Customers',
  sellers: 'Sellers',
  purchases: 'Purchases',
  suppliers: 'Suppliers',
  expenses: 'Expenses',
  reports: 'Reports',
  stores: 'Stores',
  users: 'Users',
  'audit-logs': 'Audit Logs',
  settings: 'Settings',
  profile: 'My Profile',
  business: 'Business',
  'my-sales': 'My Sales',
}
